[package]
name = "hashstore"
version = "0.1.0"
authors = ["Nathan Wilcox <nejucomo@gmail.com>"]

[dependencies]
blake2-rfc = { git = "https://github.com/cesarb/blake2-rfc" }
rustc-serialize = "0.3.15"
clap = "2.14.0"
